### ISSUE TITLE
Error on opening project

### ISSUE THREAD

**Issue by nicky508** [zorzr/TSL#4]
After creating a new project, TSL will open the project and throws an error:

`...\TSL-master>python main.py
Traceback (most recent call last):
  File "...\TSL-master\gui.py", line 114, in project_dialog
    self.controller.to_labeler(project=project)
  File "...\TSL-master\main.py", line 34, in to_labeler
    self.labeler.plot_canvas.init()
  File "...\TSL-master\core.py", line 195, in init
    self.core.plot()
  File "...\TSL-master\core.py", line 58, in plot
    plotter = Plotter(subplot, draw_set, self.timestamp, norm)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\TSL-master\plotter.py", line 39, in __init__
    self.draw()
  File "...\TSL-master\plotter.py", line 75, in draw
    self.plot.lines.append(self.plot.lines.pop(0))
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ArtistList' object has no attribute 'append'`

Launching the main.py again and opening the just created project, throws the same error. Any ideas, how to solve?

**Comment by vladBaciu** [comment]
Just try to do. For me it worked

`self.plot.add_line(self.plot.get_lines()[0])`
